from pathlib import Path


def test_agentic_workflow_source_and_lockfile_are_checked_in() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    workflow_md = repo_root / ".github" / "workflows" / "test-scholar-search.md"
    workflow_lock = (
        repo_root / ".github" / "workflows" / "test-scholar-search.lock.yml"
    )

    workflow_source_content = workflow_md.read_text()
    workflow_lock_content = workflow_lock.read_text()

    assert "mcp-servers:" in workflow_source_content
    assert "scholar-search:" in workflow_source_content
    assert (
        'search_papers(query="graph neural networks", limit=5)'
        in workflow_source_content
    )
    assert "search_papers_bulk" in workflow_source_content
    assert "search_papers_match" in workflow_source_content
    assert "create at most one GitHub" in workflow_source_content

    assert "automatically generated by gh-aw" in workflow_lock_content
    assert 'name: "Test Scholar Search MCP"' in workflow_lock_content
    assert "github/gh-aw/actions/setup@" in workflow_lock_content
    assert "{{#runtime-import .github/workflows/test-scholar-search.md}}" in (
        workflow_lock_content
    )


def test_agentic_workflow_documentation_stays_in_sync() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    readme = (repo_root / "README.md").read_text()
    handoff = (repo_root / "docs" / "agent-handoff.md").read_text()
    golden_paths = (repo_root / "docs" / "golden-paths.md").read_text()
    instructions = (repo_root / ".github" / "copilot-instructions.md").read_text()

    compile_command = "gh aw compile test-scholar-search --dir .github/workflows"

    assert ".github/workflows/test-scholar-search.md" in readme
    assert ".github/workflows/test-scholar-search.lock.yml" in readme
    assert compile_command in readme

    assert ".github/workflows/test-scholar-search.md" in handoff
    assert ".github/workflows/test-scholar-search.lock.yml" in handoff
    assert compile_command in handoff

    assert ".github/workflows/test-scholar-search.md" in golden_paths
    assert compile_command in instructions
