from pathlib import Path

from scholar_search_mcp.models.tools import TOOL_INPUT_MODELS


def _extract_allowed_tools(workflow_source_content: str) -> list[str]:
    lines = workflow_source_content.splitlines()
    allowed_tools: list[str] = []
    in_allowed_block = False

    for line in lines:
        stripped = line.strip()
        if stripped == "allowed:":
            in_allowed_block = True
            continue
        if not in_allowed_block:
            continue
        if line.startswith("      - "):
            allowed_tools.append(stripped[2:].strip())
            continue
        break

    return allowed_tools


def test_agentic_workflow_source_and_lockfile_are_checked_in() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    workflow_md = repo_root / ".github" / "workflows" / "test-scholar-search.md"
    workflow_lock = (
        repo_root / ".github" / "workflows" / "test-scholar-search.lock.yml"
    )

    workflow_source_content = workflow_md.read_text()
    workflow_lock_content = workflow_lock.read_text()
    allowed_tools = set(_extract_allowed_tools(workflow_source_content))

    expected_allowed_tools = {
        "search_papers",
        "search_papers_bulk",
        "search_papers_core",
        "search_papers_semantic_scholar",
        "search_papers_serpapi",
        "search_papers_arxiv",
        "search_papers_match",
        "get_paper_details",
        "get_paper_citations",
        "get_paper_references",
        "search_authors",
        "get_author_info",
        "get_author_papers",
        "get_paper_citation_formats",
    }

    assert "mcp-servers:" in workflow_source_content
    assert "scholar-search:" in workflow_source_content
    assert "primary Scholar Search MCP golden paths" in workflow_source_content
    assert (
        'search_papers(query="graph neural networks", limit=5)'
        in workflow_source_content
    )
    assert "search_papers_bulk" in workflow_source_content
    assert "search_papers_match" in workflow_source_content
    assert "search_authors(query=\"Yoshua Bengio\", limit=3)" in workflow_source_content
    assert (
        "search_papers_serpapi(query=\"Attention Is All You Need\", limit=3)"
        in workflow_source_content
        )
    assert "create at most one GitHub" in workflow_source_content
    assert allowed_tools == expected_allowed_tools
    assert allowed_tools <= set(TOOL_INPUT_MODELS)
    assert len(set(TOOL_INPUT_MODELS) - allowed_tools) > 0

    assert "automatically generated by gh-aw" in workflow_lock_content
    assert 'name: "Test Scholar Search MCP"' in workflow_lock_content
    assert "github/gh-aw/actions/setup@" in workflow_lock_content
    assert "{{#runtime-import .github/workflows/test-scholar-search.md}}" in (
        workflow_lock_content
    )


def test_agentic_workflow_documentation_stays_in_sync() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    readme = (repo_root / "README.md").read_text()
    handoff = (repo_root / "docs" / "agent-handoff.md").read_text()
    golden_paths = (repo_root / "docs" / "golden-paths.md").read_text()
    instructions = (repo_root / ".github" / "copilot-instructions.md").read_text()
    validate_workflow = (
        repo_root / ".github" / "workflows" / "validate.yml"
    ).read_text()

    compile_command = "gh aw compile test-scholar-search --dir .github/workflows"

    assert ".github/workflows/test-scholar-search.md" in readme
    assert ".github/workflows/test-scholar-search.lock.yml" in readme
    assert compile_command in readme

    assert ".github/workflows/test-scholar-search.md" in handoff
    assert ".github/workflows/test-scholar-search.lock.yml" in handoff
    assert compile_command in handoff
    assert "workflow_dispatch" in readme
    assert "The workflow is \"deployed\" when GitHub" in readme
    assert "pull requests cannot silently drift out of sync" in readme

    assert ".github/workflows/test-scholar-search.md" in golden_paths
    assert compile_command in instructions
    assert "Install gh-aw" in validate_workflow
    assert "GH_TOKEN: ${{ github.token }}" in validate_workflow
    assert compile_command in validate_workflow
    assert (
        "pre-commit run --files .github/workflows/test-scholar-search.lock.yml || true"
        in validate_workflow
    )
    assert "pre-commit run --files .github/workflows/test-scholar-search.lock.yml" in (
        validate_workflow
    )
    assert "git diff --exit-code -- .github/workflows/test-scholar-search.lock.yml" in (
        validate_workflow
    )
